#!/usr/bin/env python3
"""
nomad setup — Interactive configuration wizard.
Creates .env file with Telegram bot token and chat ID.
"""

import os
import sys
import subprocess
import json
from pathlib import Path

CONFIG_DIR = Path(__file__).parent
ENV_FILE = CONFIG_DIR / ".env"


def check_python():
    if sys.version_info < (3, 10):
        print(f"  ✗ Python 3.10+ required (found {sys.version})")
        sys.exit(1)
    print(f"  ✓ Python {sys.version_info.major}.{sys.version_info.minor}")


def check_docker():
    try:
        r = subprocess.run(["docker", "--version"], capture_output=True, timeout=5)
        if r.returncode == 0:
            print(f"  ✓ Docker found")
            return True
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    print("  ⚠ Docker not found — container monitoring disabled")
    return False


def check_psutil():
    try:
        import psutil
        print(f"  ✓ psutil available")
        return True
    except ImportError:
        print("  ⚠ psutil not installed — process monitoring limited")
        return False


def install_deps():
    print("\n  Installing dependencies...")
    req = CONFIG_DIR / "requirements.txt"
    if req.exists():
        r = subprocess.run(
            [sys.executable, "-m", "pip", "install", "-q", "-r", str(req)],
            capture_output=True, text=True
        )
        if r.returncode == 0:
            print("  ✓ Dependencies installed")
        else:
            print(f"  ✗ pip install failed: {r.stderr[:200]}")
            return False
    return True


def setup_telegram():
    print("\n  ── Telegram Setup ──")
    print("  To receive alerts, create a Telegram bot:")
    print("  1. Open Telegram, message @BotFather")
    print("  2. Send /newbot, follow the prompts")
    print("  3. Copy the bot token")
    print()

    token = input("  Bot token (or press Enter to skip): ").strip()
    if not token:
        print("  Skipping Telegram setup — alerts will only log to file")
        return None, None

    print(f"\n  Now send /start to your bot, then get your chat ID:")
    print("  Option A: Message @userinfobot — it replies with your ID")
    print("  Option B: Send any message to your bot, then I'll fetch it")
    print()

    chat_id = input("  Your chat ID: ").strip()
    if not chat_id:
        print("  Skipping chat ID — Telegram alerts disabled")
        return token, None

    return token, chat_id


def setup_config():
    print("\n  ── nomad Setup ──\n")

    # Check prerequisites
    print("  Checking prerequisites...")
    check_python()
    has_docker = check_docker()
    has_psutil = check_psutil()

    # Install dependencies
    install_deps()

    # Non-interactive (curl | bash) fallback — default config, no prompts
    if not sys.stdin.isatty():
        print("  Non-interactive install — writing default config (no Telegram, 30s interval)")
        ENV_FILE.write_text("# nomad configuration — generated by setup wizard\nNOMAD_SCAN_INTERVAL=30\n")
        print(f"  ✓ Config saved to {ENV_FILE}")
        print("  Run 'python3 setup.py' later to configure Telegram alerts.")
        return

    # Telegram
    token, chat_id = setup_telegram()

    # Scan interval
    print("\n  ── Scan Settings ──")
    interval = input("  Scan interval in seconds [30]: ").strip()
    interval = int(interval) if interval.isdigit() else 30

    # Write .env
    env_lines = [
        f"# nomad configuration — generated by setup wizard",
        f"NOMAD_SCAN_INTERVAL={interval}",
    ]
    if token:
        env_lines.append(f"NOMAD_TELEGRAM_TOKEN={token}")
    if chat_id:
        env_lines.append(f"NOMAD_TELEGRAM_CHAT_ID={chat_id}")

    ENV_FILE.write_text("\n".join(env_lines) + "\n")
    print(f"\n  ✓ Config saved to {ENV_FILE}")

    # Summary
    print("\n  ── Summary ──")
    print(f"  Scan interval: {interval}s")
    print(f"  Telegram: {'active' if token and chat_id else 'disabled'}")
    print(f"  Docker: {'enabled' if has_docker else 'disabled'}")
    print(f"  Process monitoring: {'full' if has_psutil else 'basic'}")
    print(f"\n  Next steps:")
    print(f"    python3 {CONFIG_DIR}/cli.py scan       # one-shot scan")
    print(f"    python3 {CONFIG_DIR}/cli.py watch       # continuous monitoring")
    print(f"    python3 {CONFIG_DIR}/dashboard.py       # web dashboard on :5010")
    print()


if __name__ == "__main__":
    setup_config()
